package app.silva.manager.ui.theme

import androidx.compose.ui.graphics.Color

// Light palette
val rv_theme_light_primary              = Color(0xFF006B8F)
val rv_theme_light_onPrimary            = Color(0xFFFFFFFF)
val rv_theme_light_primaryContainer     = Color(0xFFB3E8FF)
val rv_theme_light_onPrimaryContainer   = Color(0xFF001F2A)
val rv_theme_light_secondary            = Color(0xFF006879)
val rv_theme_light_onSecondary          = Color(0xFFFFFFFF)
val rv_theme_light_secondaryContainer   = Color(0xFFA2ECF8)
val rv_theme_light_onSecondaryContainer = Color(0xFF001F24)
val rv_theme_light_tertiary             = Color(0xFF5C4E8A)
val rv_theme_light_onTertiary           = Color(0xFFFFFFFF)
val rv_theme_light_tertiaryContainer    = Color(0xFFE8DFFF)
val rv_theme_light_onTertiaryContainer  = Color(0xFF180049)
val rv_theme_light_error                = Color(0xFFBA1A1A)
val rv_theme_light_errorContainer       = Color(0xFFFFDAD6)
val rv_theme_light_onError              = Color(0xFFFFFFFF)
val rv_theme_light_onErrorContainer     = Color(0xFF410002)
val rv_theme_light_background           = Color(0xFFF0F8FF)
val rv_theme_light_onBackground         = Color(0xFF001824)
val rv_theme_light_surface              = Color(0xFFF0F8FF)
val rv_theme_light_onSurface            = Color(0xFF001824)
val rv_theme_light_surfaceVariant       = Color(0xFFD9ECF8)
val rv_theme_light_onSurfaceVariant     = Color(0xFF3E5565)
val rv_theme_light_outline              = Color(0xFF6B8AA0)
val rv_theme_light_inverseOnSurface     = Color(0xFFE9F5FF)
val rv_theme_light_inverseSurface       = Color(0xFF2A3640)
val rv_theme_light_inversePrimary       = Color(0xFF5CD5FF)
val rv_theme_light_surfaceTint          = Color(0xFF006B8F)
val rv_theme_light_outlineVariant       = Color(0xFFBDD4E4)
val rv_theme_light_scrim                = Color(0xFF000000)

// Dark palette
val rv_theme_dark_primary              = Color(0xFF00D9FF)   // electric neon cyan
val rv_theme_dark_onPrimary            = Color(0xFF00222E)
val rv_theme_dark_primaryContainer     = Color(0xFF004560)
val rv_theme_dark_onPrimaryContainer   = Color(0xFFB3EEFF)
val rv_theme_dark_secondary            = Color(0xFF7ECFDF)
val rv_theme_dark_onSecondary          = Color(0xFF003540)
val rv_theme_dark_secondaryContainer   = Color(0xFF004E5E)
val rv_theme_dark_onSecondaryContainer = Color(0xFFB2EBF2)
val rv_theme_dark_tertiary             = Color(0xFFB39DDB)
val rv_theme_dark_onTertiary           = Color(0xFF1A0035)
val rv_theme_dark_tertiaryContainer    = Color(0xFF3D2A6B)
val rv_theme_dark_onTertiaryContainer  = Color(0xFFEDE0FF)
val rv_theme_dark_error                = Color(0xFFFFB4AB)
val rv_theme_dark_errorContainer       = Color(0xFF93000A)
val rv_theme_dark_onError              = Color(0xFF690005)
val rv_theme_dark_onErrorContainer     = Color(0xFFFFDAD6)
val rv_theme_dark_background           = Color(0xFF0B0F17)   // deep space near-black
val rv_theme_dark_onBackground         = Color(0xFFE0EFF8)
val rv_theme_dark_surface              = Color(0xFF111827)   // dark navy
val rv_theme_dark_onSurface            = Color(0xFFE0EFF8)
val rv_theme_dark_surfaceVariant       = Color(0xFF1C2840)   // muted blue-gray
val rv_theme_dark_onSurfaceVariant     = Color(0xFF9DB8D0)
val rv_theme_dark_outline              = Color(0xFF2A4060)
val rv_theme_dark_inverseOnSurface     = Color(0xFF111827)
val rv_theme_dark_inverseSurface       = Color(0xFFE0EFF8)
val rv_theme_dark_inversePrimary       = Color(0xFF005F7A)
val rv_theme_dark_surfaceTint          = Color(0xFF00D9FF)
val rv_theme_dark_outlineVariant       = Color(0xFF1C2840)
val rv_theme_dark_scrim                = Color(0xFF000000)

// Accent constants used in custom UI draws
val NexusCyan   = Color(0xFF00D9FF)
val NexusGlow   = Color(0xFF00AACC)
val NexusDark   = Color(0xFF0B0F17)
